http:
  middlewares:
    # Basic Auth for dashboard
    dashboard-auth:
      basicAuth:
        users:
          - "{someusername}:{somepassword}" # Use htpasswd -nB user to create
    ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.50.0/24"  # Only local network
    rate-limit:
      rateLimit:
        burst: 100
        average: 50

  routers:
    # Dashboard router with authentication
    dashboard:
      rule: "Host(`traefik.local`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: api@internal
      middlewares:
        - dashboard-auth

    # LLM service
    llm-service:
      rule: "Host(`llm.ai.home`)"
      service: llm-service

  services:
    llm-service:
      loadBalancer:
        servers:
          - url: "http://192.168.50.210:3000"